linters-settings:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gofmt
    - goimports
    - golint
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - vet
    - gosimple
    - structcheck
    - varcheck
    - typecheck

run:
  deadline: 5m
  enable:
    - vetshadow
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gosumcheck
