services:
  postgres:
    image: postgres:latest
    container_name: postgres_go2
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # env_file: ./app.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  go_app:
    build: .
    container_name: go_app_container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - ./.env
    volumes:
      - uploaded_files:/app/static
      - log_files:/app/logs

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - go_app

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path /var/www/certbot/ -d ${BASE_URL}
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
      - nginx

volumes:
  postgres_data:
  uploaded_files:
  log_files:
