development:
  debug_mode: true

production:
  debug_mode: false

server_port: 8080
log_file: logs/app.log
feature_enabled: true
max_items_per_page: 50
static_path: static
static_images_path: static/images
