name: Deploy to DigitalOcean Droplet (Prod)

on:
  push:
    branches:
      - main

jobs:
  deploy_prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

        # to prevent host key verification failed
    #   - name: Configure SSH known hosts
    #     run: ssh-keyscan -H ${{ secrets.DROPLET_IP_ADDRESS }} >> ~/.ssh/known_hosts
        

          # this will make SSL certificate from certbot gone , dont hard reset 
      # - name: Connect to Droplet -> Reset Main Branch
      #   run: |
      #     ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP_ADDRESS }} 'cd /root/projects/rentvehicles && git reset --hard HEAD && git checkout main && git fetch origin && git reset --hard origin/main'

      - name: Test SSH connection to Droplet
        run: ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP_ADDRESS }} exit

      - name: Create Backup Directory for Certbot
        run: ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP_ADDRESS }} 'mkdir -p /root/projects/backup/certbot'

      - name: Backup Certbot SSL Certificates
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP_ADDRESS }} 'cp -R /root/projects/rentvehicles/certbot/* /root/projects/backup/certbot/'

      - name: Connect to Droplet -> Reset Main Branch
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP_ADDRESS }} 'cd /root/projects/rentvehicles && git reset --hard HEAD && git checkout main && git fetch origin && git reset --hard origin/main'

      - name: Connect to Droplet -> Recover Deleted Certbot SSL Certificates By Hard Reset
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP_ADDRESS }} 'cp -R /root/projects/backup/certbot/* /root/projects/rentvehicles/certbot/'

      - name: Connect to Droplet -> Rebuild & Rerun Docker Compose Services
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP_ADDRESS }} 'cd /root/projects/rentvehicles && docker compose -f docker-compose-prod.yml down && docker compose -f docker-compose-prod.yml up -d --build'
